export type CashFlow={date:string;amount:number;label?:string}
export type IrrBien={irr:number|null;flows:CashFlow[];initialEquity:number;terminalEquity:number;remainingDebt:number;reason?:string}

type Bien={date_acquisition?:string|null;prix_achat?:number|null;frais_notaire?:number|null;frais_agence?:number|null;frais_courtage?:number|null;autres_frais_acquisition?:number|null;valeur_actuelle?:number|null;valeur_actuelle_date?:string|null}
type Paiement={montant?:number|null;statut?:string|null;date_paiement?:string|null}
type Depense={montant?:number|null;date_depense?:string|null}
type Financement={montant_emprunte?:number|null;taux_nominal?:number|null;mensualite?:number|null;assurance_mensuelle?:number|null;date_debut?:string|null;date_fin?:string|null;duree_mois?:number|null}
const DAY=86400000,n=(v:number|null|undefined)=>Number(v??0)
const dateOnly=(s:string)=>new Date(`${s.slice(0,10)}T00:00:00`)
const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
const monthsBetween=(a:Date,b:Date)=>Math.max(0,(b.getFullYear()-a.getFullYear())*12+b.getMonth()-a.getMonth()+(b.getDate()>=a.getDate()?1:0))
function addMonths(d:Date,k:number){const x=new Date(d);x.setMonth(x.getMonth()+k);return x}
export function xirr(flows:CashFlow[]){const f=flows.filter(x=>Number.isFinite(x.amount)&&x.amount!==0).sort((a,b)=>a.date.localeCompare(b.date));if(f.length<2||!f.some(x=>x.amount<0)||!f.some(x=>x.amount>0))return null;const d0=dateOnly(f[0].date);const npv=(r:number)=>f.reduce((s,x)=>s+x.amount/Math.pow(1+r,(dateOnly(x.date).getTime()-d0.getTime())/DAY/365),0);let lo=-.9999,hi=1,a=npv(lo),b=npv(hi),guard=0;while(a*b>0&&hi<1e6&&guard++<60){hi=hi*2+1;b=npv(hi)}if(!Number.isFinite(a)||!Number.isFinite(b)||a*b>0)return null;for(let i=0;i<160;i++){const mid=(lo+hi)/2,m=npv(mid);if(Math.abs(m)<1e-7)return mid;if(a*m<=0){hi=mid;b=m}else{lo=mid;a=m}}return(lo+hi)/2}
export function remainingLoanBalance(fin:Financement|null|undefined,at:string){if(!fin||!fin.montant_emprunte||!fin.date_debut)return 0;const principal=n(fin.montant_emprunte),start=dateOnly(fin.date_debut),end=dateOnly(at);if(end<start)return principal;const duration=n(fin.duree_mois)||9999,k=Math.min(duration,monthsBetween(start,end));if(k>=duration)return 0;const payment=n(fin.mensualite),r=n(fin.taux_nominal)/100/12;if(payment<=0)return principal;if(r===0)return Math.max(0,principal-payment*k);const p=Math.pow(1+r,k);return Math.max(0,principal*p-payment*(p-1)/r)}
export function investmentIrr(bien:Bien,paiements:Paiement[],depenses:Depense[],fin?:Financement|null):IrrBien{const acquisition=bien.date_acquisition?.slice(0,10),terminal=bien.valeur_actuelle_date?.slice(0,10),value=n(bien.valeur_actuelle);if(!acquisition)return{irr:null,flows:[],initialEquity:0,terminalEquity:0,remainingDebt:0,reason:"Date d’acquisition manquante"};if(!terminal||value<=0)return{irr:null,flows:[],initialEquity:0,terminalEquity:0,remainingDebt:0,reason:'Valeur actuelle ou date d’estimation manquante'};if(terminal<=acquisition)return{irr:null,flows:[],initialEquity:0,terminalEquity:0,remainingDebt:0,reason:"La date d’estimation doit être postérieure à l’acquisition"};const cost=n(bien.prix_achat)+n(bien.frais_notaire)+n(bien.frais_agence)+n(bien.frais_courtage)+n(bien.autres_frais_acquisition),borrowed=n(fin?.montant_emprunte),initialEquity=Math.max(0,cost-borrowed);if(cost<=0||initialEquity<=0)return{irr:null,flows:[],initialEquity,terminalEquity:0,remainingDebt:0,reason:"Coût d’acquisition ou fonds propres insuffisants"};const flows:CashFlow[]=[{date:acquisition,amount:-initialEquity,label:'Fonds propres investis'}];for(const p of paiements){const d=p.date_paiement?.slice(0,10);if(d&&d>=acquisition&&d<=terminal&&['recu','partiel'].includes(String(p.statut)))flows.push({date:d,amount:n(p.montant),label:'Encaissement'})}for(const d of depenses){const dt=d.date_depense?.slice(0,10);if(dt&&dt>=acquisition&&dt<=terminal)flows.push({date:dt,amount:-n(d.montant),label:'Dépense'})}if(fin?.date_debut&&n(fin.mensualite)+n(fin.assurance_mensuelle)>0){const start=dateOnly(fin.date_debut),term=dateOnly(terminal),duration=n(fin.duree_mois)||9999;for(let k=0;k<duration;k++){const d=addMonths(start,k);if(d>term)break;const ds=iso(d);if(ds>=acquisition)flows.push({date:ds,amount:-(n(fin.mensualite)+n(fin.assurance_mensuelle)),label:'Crédit + assurance'})}}const remainingDebt=remainingLoanBalance(fin,terminal),terminalEquity=Math.max(0,value-remainingDebt);flows.push({date:terminal,amount:terminalEquity,label:'Valeur nette actuelle'});return{irr:xirr(flows),flows,initialEquity,terminalEquity,remainingDebt}}
export function portfolioIrr(items:{bien:Bien;paiements:Paiement[];depenses:Depense[];fin?:Financement|null}[]){const flows:CashFlow[]=[];for(const x of items){const r=investmentIrr(x.bien,x.paiements,x.depenses,x.fin);if(r.reason)return null;flows.push(...r.flows)}return xirr(flows)}
