'use client'
import {useState} from 'react'
import {useRouter} from 'next/navigation'
import {enregistrerValeurActuelle} from './actions'

type Metric={label:string;value:string;help:string;formula:string;detail:string}
export default function PerformanceCard({bienId,metrics,valeur,dateValeur}:{bienId:string;metrics:Metric[];valeur:number|null;dateValeur:string|null}){
 const router=useRouter(),[open,setOpen]=useState<string|null>(null),[editing,setEditing]=useState(!valeur),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError(null);const r=await enregistrerValeurActuelle(bienId,new FormData(e.currentTarget));setLoading(false);if(r?.error)setError(r.error);else{setEditing(false);router.refresh()}}
 return <div className="mt-6 bg-white rounded-2xl border p-6"><div className="flex justify-between items-start gap-4 mb-5"><div><h2 className="text-lg font-semibold">Performance de l’investissement</h2><p className="text-sm text-slate-500 mt-1">Indicateurs calculés à partir des données enregistrées pour ce bien.</p></div>{!editing&&<button type="button" onClick={()=>setEditing(true)} className="text-sm text-blue-600 whitespace-nowrap">Mettre à jour la valeur</button>}</div>
 <div className="grid sm:grid-cols-2 lg:grid-cols-5 border rounded-xl overflow-hidden">{metrics.map(m=><div key={m.label} className="p-4 border-b sm:border-b-0 sm:border-r last:border-r-0 relative"><div className="flex items-center gap-1.5"><p className="text-xs text-slate-500">{m.label}</p><button type="button" aria-label={`Explication ${m.label}`} onClick={()=>setOpen(open===m.label?null:m.label)} className="w-4 h-4 rounded-full border text-[10px] leading-none text-slate-500">i</button></div><p className="font-semibold text-lg mt-1">{m.value}</p>{open===m.label&&<div className="absolute z-20 left-2 right-2 top-16 bg-slate-900 text-white rounded-xl p-3 text-xs shadow-xl"><p>{m.help}</p><p className="mt-2 text-slate-300"><b>Formule :</b> {m.formula}</p><p className="mt-2 text-slate-300"><b>Calcul :</b> {m.detail}</p></div>}</div>)}</div>
 {editing&&<form onSubmit={save} className="mt-5 rounded-xl bg-slate-50 border p-4"><p className="text-sm font-medium mb-3">Valeur actuelle du bien</p><div className="grid sm:grid-cols-[1fr_1fr_auto] gap-3 items-end"><div><label className="text-xs text-slate-500">Valeur estimée (€)</label><input name="valeur_actuelle" type="number" min="1" step="0.01" defaultValue={valeur??''} className="w-full border rounded-lg px-3 py-2 bg-white"/></div><div><label className="text-xs text-slate-500">Date de l’estimation</label><input name="valeur_actuelle_date" type="date" defaultValue={dateValeur??new Date().toISOString().slice(0,10)} className="w-full border rounded-lg px-3 py-2 bg-white"/></div><button disabled={loading} className="bg-blue-600 text-white rounded-lg px-4 py-2 text-sm disabled:opacity-50">{loading?'Enregistrement…':'Enregistrer'}</button></div>{error&&<p className="text-sm text-red-600 mt-2">{error}</p>}<p className="text-xs text-slate-500 mt-2">Indiquez une estimation réaliste et actualisez-la lorsque vous disposez d’une nouvelle valeur. Elle est utilisée pour le TRI.</p></form>}
 </div>
}
