'use server'
import { createClient } from '@/lib/supabase/server'
import { revalidatePath } from 'next/cache'
const NON_HABITABLE=new Set(['parking','box','garage','cave','autre'])
type LotInput={id?:string;numero_lot:string;type:string;specificite?:string;surface_m2:string;nb_pieces:string;type_location:string;dpe?:string;estimation_conso_annuelle?:string;prix_mensuel?:string;annexes?:string[];rattachement_type?:string;parent_lot_id?:string|null;locataire_externe_nom?:string;locataire_externe_email?:string}
const optional=(v:FormDataEntryValue|null)=>v&&String(v).trim()?String(v):null
export async function modifierBien(id:string,formData:FormData){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)return{error:'Vous devez être connecté.'}
 const type=String(formData.get('type')??''), immeuble=type==='immeuble'||type==='immeuble_rapport', surface=formData.get('surface_m2'), surfaceLocative=formData.get('surface_locative_m2'), pieces=formData.get('nb_pieces'), lotsCount=formData.get('nb_lots'), prix=formData.get('prix_achat'), conso=formData.get('estimation_conso_annuelle'), annexes=formData.getAll('annexes') as string[], lotsJson=formData.get('lots_json') as string|null
 const {error}=await supabase.from('biens').update({nom:String(formData.get('nom')??''),adresse:String(formData.get('adresse')??''),ville:String(formData.get('ville')??''),code_postal:String(formData.get('code_postal')??''),type,type_location:NON_HABITABLE.has(type)?null:((formData.get('type_location') as string)||null),specificite:(formData.get('specificite') as string)||null,parent_bien_id:(formData.get('parent_bien_id') as string)||null,rattachement_type:(formData.get('rattachement_type') as string)||null,locataire_externe_nom:(formData.get('locataire_externe_nom') as string)||null,locataire_externe_email:(formData.get('locataire_externe_email') as string)||null,surface_m2:!immeuble&&surface?Number(surface):null,surface_totale_m2:immeuble&&surface?Number(surface):null,surface_locative_m2:immeuble&&surfaceLocative?Number(surfaceLocative):null,nb_pieces:!immeuble&&pieces?Number(pieces):null,nb_lots:immeuble?Number(lotsCount||0):null,prix_achat:prix?Number(prix):null,annexes,date_acquisition:optional(formData.get('date_acquisition')),date_mise_location:optional(formData.get('date_mise_location')),date_construction:optional(formData.get('date_construction')),date_renovation:optional(formData.get('date_renovation')),dpe:optional(formData.get('dpe')),estimation_conso_annuelle:conso?Number(conso):null}).eq('id',id).eq('proprietaire_id',user.id)
 if(error)return{error:error.message}
 if(immeuble&&lotsJson){let lots:LotInput[];try{lots=JSON.parse(lotsJson)}catch{return{error:'Le détail des lots est invalide.'}}
  const {data:existing,error:readError}=await supabase.from('lots').select('id').eq('bien_id',id).eq('proprietaire_id',user.id);if(readError)return{error:readError.message}
  const keptIds=lots.map(l=>l.id).filter(Boolean) as string[];const removed=(existing??[]).map(x=>x.id).filter(x=>!keptIds.includes(x));
  if(removed.length){await supabase.from('lots').update({parent_lot_id:null}).eq('bien_id',id).in('parent_lot_id',removed);const{error:delError}=await supabase.from('lots').delete().eq('bien_id',id).eq('proprietaire_id',user.id).in('id',removed);if(delError)return{error:delError.message}}
  for(let i=0;i<lots.length;i++){const l=lots[i];const hab=['appartement','studio'].includes(l.type),ratt=['box','parking','garage','cave'].includes(l.type);const row={numero_lot:`Lot ${i+1}`,type:l.type||'appartement',specificite:hab?(l.specificite||null):null,type_location:l.type_location||null,dpe:hab?(l.dpe||null):null,estimation_conso_annuelle:hab&&l.estimation_conso_annuelle?Number(l.estimation_conso_annuelle):null,prix_mensuel:ratt&&l.prix_mensuel!==undefined&&l.prix_mensuel!==''?Number(l.prix_mensuel):null,surface_m2:l.surface_m2?Number(l.surface_m2):null,nb_pieces:l.nb_pieces?Number(l.nb_pieces):null,annexes:l.annexes??[],rattachement_type:l.rattachement_type||null,parent_lot_id:l.rattachement_type==='lot'?(l.parent_lot_id||null):null,locataire_externe_nom:l.rattachement_type==='locataire_externe'?(l.locataire_externe_nom||null):null,locataire_externe_email:l.rattachement_type==='locataire_externe'?(l.locataire_externe_email||null):null};if(l.id){const{error:e}=await supabase.from('lots').update(row).eq('id',l.id).eq('bien_id',id).eq('proprietaire_id',user.id);if(e)return{error:e.message}}else{const{error:e}=await supabase.from('lots').insert({...row,bien_id:id,proprietaire_id:user.id});if(e)return{error:e.message}}}
 }
 revalidatePath('/dashboard');revalidatePath('/dashboard/biens');revalidatePath(`/dashboard/biens/${id}`);return{ok:true}
}
