import Link from 'next/link'
import {createClient} from '@/lib/supabase/server'
const euro=(v:number|null)=>v==null?'—':new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(v)
const date=(v:string|null)=>v?new Intl.DateTimeFormat('fr-FR').format(new Date(`${v}T00:00:00`)):'—'
function monthsBetween(a:Date,b:Date){return Math.max(0,(b.getFullYear()-a.getFullYear())*12+b.getMonth()-a.getMonth())}
function remainingMonths(c:any){if(c.date_fin){const end=new Date(`${c.date_fin}T00:00:00`),now=new Date();return end<=now?0:Math.max(0,(end.getFullYear()-now.getFullYear())*12+end.getMonth()-now.getMonth())}if(c.duree_mois!=null&&c.date_debut){return Math.max(0,Number(c.duree_mois)-monthsBetween(new Date(`${c.date_debut}T00:00:00`),new Date()))}return null}
function term(v:number|null){if(v==null)return'—';if(v===0)return'Terminé';const y=Math.floor(v/12),m=v%12;return[y?`${y} an${y>1?'s':''}`:'',m?`${m} mois`:''].filter(Boolean).join(' ')}
function crd(c:any){const p=Number(c.montant_emprunte??0),payment=Number(c.mensualite??0),annual=Number(c.taux_nominal??0);if(!p||!c.date_debut)return null;const elapsed=monthsBetween(new Date(`${c.date_debut}T00:00:00`),new Date());if(elapsed<=0)return p;if(payment<=0)return null;const r=annual/100/12;if(r===0)return Math.max(0,p-payment*elapsed);const balance=p*Math.pow(1+r,elapsed)-payment*((Math.pow(1+r,elapsed)-1)/r);return Math.max(0,balance)}
export default async function CreditsPage(){const s=await createClient();const{data:{user}}=await s.auth.getUser();const{data:credits}=await s.from('financements').select('*, biens(id,nom,adresse,ville)').eq('proprietaire_id',user?.id??'').order('created_at',{ascending:false});return <div className="p-6 max-w-7xl mx-auto"><div className="flex items-center justify-between gap-4 mb-7"><div><h1 className="text-2xl font-bold">Crédits</h1><p className="text-slate-500 mt-1">Gérez les financements rattachés à votre patrimoine.</p></div><Link href="/dashboard/credits/nouveau" className="bg-blue-600 text-white px-4 py-2.5 rounded-xl text-sm font-medium whitespace-nowrap">+ Ajouter un crédit</Link></div>{!credits?.length?<div className="bg-white border rounded-2xl p-8 text-center"><h2 className="font-semibold">Aucun crédit enregistré</h2><p className="text-sm text-slate-500 mt-2">Ajoutez un financement puis rattachez-le au bien concerné.</p></div>:<div className="space-y-4">{credits.map((c:any)=>{const balance=crd(c),remaining=remainingMonths(c);return <div key={c.id} className="bg-white border rounded-2xl overflow-hidden"><div className="px-5 py-4 flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3 border-b border-slate-100"><div><h2 className="font-semibold text-lg">{c.biens?.nom??'Bien'}</h2><p className="text-sm text-slate-500">{c.biens?.adresse}{c.biens?.ville?`, ${c.biens.ville}`:''}</p></div><span className="text-xs bg-slate-100 rounded-full px-3 py-1 h-fit w-fit">Crédit immobilier</span></div><div className="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-8 divide-x-0 md:divide-x divide-slate-100 border-b border-slate-100"><Info l="Montant initial" v={euro(c.montant_emprunte)}/><Info l="Capital restant dû*" v={euro(balance)}/><Info l="Mensualité" v={euro(c.mensualite)}/><Info l="Assurance / mois" v={euro(c.assurance_mensuelle)}/><Info l="Taux nominal" v={c.taux_nominal==null?'—':`${c.taux_nominal} %`}/><Info l="Durée restante" v={term(remaining)}/><Info l="Début" v={date(c.date_debut)}/><Info l="Fin" v={date(c.date_fin)}/></div><div className="px-5 py-3 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2 text-sm bg-slate-50/60"><div className="flex flex-wrap gap-x-5 gap-y-2"><Link href={`/dashboard/biens/${c.bien_id}/financement`} className="text-blue-600 font-medium">Consulter / modifier</Link>{c.biens?.id&&<Link href={`/dashboard/biens/${c.biens.id}`} className="text-slate-500">Voir le bien</Link>}</div><p className="text-[11px] text-slate-400">* Estimation calculée à partir du montant, du taux, de la mensualité et de la date de début.</p></div></div>})}</div>}</div>}
function Info({l,v}:{l:string;v:string}){return <div className="px-4 py-4 min-w-0"><p className="text-xs text-slate-400 mb-1">{l}</p><p className="font-medium text-sm break-words">{v}</p></div>}
