'use client'

import { useMemo,useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'
import { useEffect } from 'react'

type Depense={id:string;bien_id:string|null;categorie:string;montant:number;date_depense:string;description:string|null;deductible_fiscalement:boolean}
type Bien={id:string;nom:string;ville:string}
const labels:Record<string,string>={travaux:'Travaux',charges:'Charges',assurance:'Assurance',gestion:'Gestion',taxe:'Taxe',autre:'Autre'}
const euro=(v:number)=>v.toLocaleString('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:2})
const fmt=(d:string)=>new Date(`${d}T00:00:00`).toLocaleDateString('fr-FR',{day:'2-digit',month:'short',year:'numeric'})
const monthName=(m:number)=>new Date(2026,m-1,1).toLocaleDateString('fr-FR',{month:'long'}).replace(/^./,c=>c.toUpperCase())

export default function DepensesPage(){
 const [loading,setLoading]=useState(true),[depenses,setDepenses]=useState<Depense[]>([]),[biens,setBiens]=useState<Bien[]>([]),[bienFilter,setBienFilter]=useState('all'),[catFilter,setCatFilter]=useState('all'),[yearFilter,setYearFilter]=useState('all'),[monthFilter,setMonthFilter]=useState('all'),[open,setOpen]=useState<Record<string,boolean>>({})
 useEffect(()=>{const s=createClient();Promise.all([s.from('depenses').select('*').order('date_depense',{ascending:false}),s.from('biens').select('id,nom,ville').order('nom')]).then(r=>{setDepenses((r[0].data??[]) as Depense[]);setBiens((r[1].data??[]) as Bien[]);setLoading(false)})},[])
 const bienMap=new Map(biens.map(b=>[b.id,b])),years=useMemo(()=>[...new Set(depenses.map(d=>d.date_depense.slice(0,4)))].sort((a,b)=>b.localeCompare(a)),[depenses])
 const filtered=useMemo(()=>depenses.filter(d=>(bienFilter==='all'||(bienFilter==='none'?!d.bien_id:d.bien_id===bienFilter))&&(catFilter==='all'||d.categorie===catFilter)&&(yearFilter==='all'||d.date_depense.startsWith(yearFilter))&&(monthFilter==='all'||d.date_depense.slice(5,7)===monthFilter)),[depenses,bienFilter,catFilter,yearFilter,monthFilter])
 const total=filtered.reduce((s,d)=>s+Number(d.montant),0)
 const groups=useMemo(()=>{const m=new Map<string,{key:string;label:string;ville:string;total:number;cats:Map<string,{total:number;items:Depense[]}>}>();filtered.forEach(d=>{const b=d.bien_id?bienMap.get(d.bien_id):null,key=d.bien_id??'none';if(!m.has(key))m.set(key,{key,label:b?.nom??'Dépenses non rattachées',ville:b?.ville??'',total:0,cats:new Map()});const g=m.get(key)!;g.total+=Number(d.montant);if(!g.cats.has(d.categorie))g.cats.set(d.categorie,{total:0,items:[]});const c=g.cats.get(d.categorie)!;c.total+=Number(d.montant);c.items.push(d)});return [...m.values()].sort((a,b)=>b.total-a.total)},[filtered,biens])
 const toggle=(k:string)=>setOpen(o=>({...o,[k]:!o[k]}))
 return <div className="p-6 max-w-6xl mx-auto">
  <div className="flex flex-wrap items-center justify-between gap-4 mb-6"><div><h1 className="text-2xl font-bold text-slate-900">Dépenses</h1><p className="text-sm text-slate-500 mt-1">{filtered.length} dépense{filtered.length!==1?'s':''} · Total affiché : <b>{euro(total)}</b></p></div><Link href="/dashboard/depenses/nouvelle" className="bg-blue-600 text-white rounded-xl px-4 py-2 text-sm font-medium hover:bg-blue-700">+ Nouvelle dépense</Link></div>
  <div className="bg-white border rounded-2xl p-4 mb-5"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500 mb-3">Filtres</p><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3"><Select value={bienFilter} onChange={setBienFilter} label="Bien"><option value="all">Tous les biens</option>{biens.map(b=><option key={b.id} value={b.id}>{b.nom}</option>)}<option value="none">Non rattachées</option></Select><Select value={catFilter} onChange={setCatFilter} label="Catégorie"><option value="all">Toutes les catégories</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select><Select value={yearFilter} onChange={v=>{setYearFilter(v);setMonthFilter('all')}} label="Année"><option value="all">Toutes les années</option>{years.map(y=><option key={y} value={y}>{y}</option>)}</Select><Select value={monthFilter} onChange={setMonthFilter} label="Mois"><option value="all">Tous les mois</option>{Array.from({length:12},(_,i)=>String(i+1).padStart(2,'0')).map((m,i)=><option key={m} value={m}>{monthName(i+1)}</option>)}</Select></div><button onClick={()=>{setBienFilter('all');setCatFilter('all');setYearFilter('all');setMonthFilter('all')}} className="text-xs text-blue-600 mt-3 hover:underline">Réinitialiser les filtres</button></div>
  {loading?<div className="h-40 bg-slate-100 rounded-2xl animate-pulse"/>:groups.length===0?<div className="bg-white border rounded-2xl p-12 text-center text-sm text-slate-400">Aucune dépense pour ces critères.</div>:<div className="space-y-4">{groups.map(g=><section key={g.key} className="bg-white border rounded-2xl overflow-hidden"><div className="px-5 py-4 bg-slate-50 flex items-center justify-between"><div><h2 className="font-semibold text-slate-900">{g.label}</h2>{g.ville&&<p className="text-xs text-slate-400">{g.ville}</p>}</div><div className="text-right"><p className="text-xs text-slate-400">Total</p><p className="font-bold">{euro(g.total)}</p></div></div><div className="divide-y">{[...g.cats.entries()].sort((a,b)=>b[1].total-a[1].total).map(([cat,c])=>{const k=`${g.key}-${cat}`,isOpen=!!open[k];return <div key={cat}><button onClick={()=>toggle(k)} className="w-full px-5 py-3 flex items-center justify-between hover:bg-slate-50 text-left"><div className="flex items-center gap-2"><span className="text-sm font-medium">{labels[cat]??cat}</span><span className="text-xs text-slate-400">{c.items.length} opération{c.items.length!==1?'s':''}</span></div><div className="flex items-center gap-3"><b className="text-sm">{euro(c.total)}</b><span className="text-slate-400">{isOpen?'−':'+'}</span></div></button>{isOpen&&<div className="border-t bg-slate-50/40 divide-y divide-slate-100">{c.items.map(d=><div key={d.id} className="px-7 py-3 flex gap-4 justify-between"><div className="min-w-0"><p className="text-sm text-slate-700 truncate">{d.description||'Sans description'}</p>{d.deductible_fiscalement&&<span className="text-[11px] text-green-700">Déductible fiscalement</span>}</div><div className="text-right shrink-0"><p className="text-sm font-medium">{euro(Number(d.montant))}</p><p className="text-xs text-slate-400">{fmt(d.date_depense)}</p></div></div>)}</div>}</div>})}</div></section>)}</div>}
 </div>
}
function Select({label,value,onChange,children}:{label:string;value:string;onChange:(v:string)=>void;children:React.ReactNode}){return <label className="text-xs text-slate-500"><span className="block mb-1">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="w-full border rounded-lg bg-white px-3 py-2 text-sm text-slate-700 outline-none focus:ring-2 focus:ring-blue-100">{children}</select></label>}
