import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { generateQuittancePdf, cleanPdfText, formatMois, MOIS_FR } from '@/lib/generateQuittancePdf'
function formatDate(d:Date){return `${String(d.getDate()).padStart(2,'0')} ${MOIS_FR[d.getMonth()]} ${d.getFullYear()}`}
function formatType(value:string){return cleanPdfText(value||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
export async function POST(req:NextRequest){try{
 const{quittanceId,otp}=await req.json();if(!quittanceId||!otp)return NextResponse.json({error:'Données manquantes'},{status:400});const supabase=await createClient();const{data:{user},error:ae}=await supabase.auth.getUser();if(ae||!user)return NextResponse.json({error:'Non autorisé'},{status:401});const{data:o,error:oe}=await supabase.from('otp_codes').select('*').eq('user_id',user.id).eq('quittance_id',quittanceId).single();if(oe||!o||o.code!==otp)return NextResponse.json({error:'Code invalide ou expiré'},{status:400});if(new Date(o.expires_at)<new Date())return NextResponse.json({error:'Code expiré'},{status:400})
 const{data:q,error}=await supabase.from('quittances').select('*, locataires(nom,email,bail_id), biens(nom,adresse,ville,type)').eq('id',quittanceId).eq('proprietaire_id',user.id).single();if(error||!q)return NextResponse.json({error:'Quittance introuvable'},{status:404});const{data:profile}=await supabase.from('profiles').select('nom,prenom,telephone,signature_base64,iban,bic').eq('id',user.id).single();const pn=`${profile?.prenom??''} ${profile?.nom??''}`.trim();if(!pn)return NextResponse.json({error:'Renseignez le prénom et le nom du bailleur dans le profil avant de générer une quittance.'},{status:400})
 let lot:any=null;if(q.locataires?.bail_id){const{data:b}=await supabase.from('baux').select('lot_id').eq('id',q.locataires.bail_id).eq('proprietaire_id',user.id).maybeSingle();if(b?.lot_id){const r=await supabase.from('lots').select('numero_lot,nom_personnalise,type,specificite,surface').eq('id',b.lot_id).maybeSingle();lot=r.data}}const{data:pays}=await supabase.from('paiements').select('commentaire').eq('proprietaire_id',user.id).eq('locataire_id',q.locataire_id).eq('mois',q.mois);const commentaire=(pays??[]).map((p:any)=>cleanPdfText(p.commentaire||'')).filter(Boolean).join(' · ');const signedAt=new Date(),ref=`EKO-${String(q.mois||'').replace('-','')}-${String(q.id).slice(0,6).toUpperCase()}`
 const typeAffiche=lot?.nom_personnalise?cleanPdfText(lot.nom_personnalise):formatType(lot?.type??q.biens?.type??'')
 const bytes=await generateQuittancePdf({locataireNom:cleanPdfText(q.locataires?.nom??'-'),locataireEmail:cleanPdfText(q.locataires?.email??''),proprietaireNom:cleanPdfText(pn),proprietaireEmail:cleanPdfText(user.email??''),proprietaireTelephone:cleanPdfText(profile?.telephone??''),bienNom:cleanPdfText(q.biens?.nom??''),bienAdresse:cleanPdfText(q.biens?.adresse??''),bienVille:cleanPdfText(q.biens?.ville??''),lotNom:cleanPdfText(lot?.numero_lot??''),typeLogement:typeAffiche,specificiteLogement:cleanPdfText(lot?.specificite??''),surface:lot?.surface,mois:q.mois,reference:ref,loyerHc:Number(q.loyer_hc??0),charges:Number(q.charges??0),solde:Number(q.solde??0),total:Number(q.total??0),commentaire,iban:cleanPdfText(profile?.iban??''),bic:cleanPdfText(profile?.bic??''),signatureDataUrl:profile?.signature_base64??'',dateSignature:formatDate(signedAt)})
 const email=q.locataires?.email;if(!email)return NextResponse.json({error:'Email locataire introuvable'},{status:400});
 const testRaw=process.env.QUITTANCE_TEST_EMAILS||process.env.QUITTANCE_TEST_EMAIL||'synteyapartners@gmail.com';
 const tests=testRaw.split(',').map(e=>e.trim()).filter(Boolean);const to=tests.length?tests:[email];const isTest=tests.length>0;const fileName=`quittance-${q.mois}-${String(q.locataires?.nom??'locataire').toLowerCase().replace(/\s+/g,'-')}.pdf`;
 const rr=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:'Ekolocs <onboarding@resend.dev>',to,subject:`${isTest?'[TEST] ':''}Quittance de loyer - ${formatMois(q.mois)}`,html:`<div style="font-family:sans-serif;max-width:480px;margin:0 auto;padding:32px"><p style="color:#64748b;font-size:12px">Mode recette — destinataire réel : ${email}</p><h2>Quittance de loyer</h2><p>Bonjour ${q.locataires?.nom??''},<br/>Veuillez trouver ci-joint votre quittance pour <strong>${formatMois(q.mois)}</strong>.</p><div style="background:#f1f5f9;border-radius:12px;padding:16px"><strong>Montant total : ${q.total} EUR</strong><p>${q.biens?.nom??''} - ${q.biens?.ville??''}</p></div></div>`,attachments:[{filename:fileName,content:Buffer.from(bytes).toString('base64')}]})});
 if(!rr.ok){const resendError=await rr.json();console.error('Resend error:',resendError);return NextResponse.json({error:'La quittance a été générée mais l’envoi par e-mail a échoué.',resendError},{status:502})};
 await supabase.from('quittances').update({envoyee:true,date_signature:signedAt.toISOString()}).eq('id',quittanceId);await supabase.from('otp_codes').delete().eq('quittance_id',quittanceId);return NextResponse.json({ok:true})
}catch(e){console.error('quittance-signer error:',e);return NextResponse.json({error:'Erreur serveur'},{status:500})}}
