import { createClient } from '@/lib/supabase/server'
import Link from 'next/link'
import DeleteBienButton from './DeleteBienButton'

type Bien = { id:string; nom:string; adresse:string; ville:string; code_postal:string; type:string; type_location:string|null; surface_m2:number|null; surface_totale_m2:number|null; nb_pieces:number|null; nb_lots:number|null; prix_achat:number|null; annexes:string[] }
const labels:Record<string,string>={appartement:'Appartement',maison:'Maison',studio:'Studio',immeuble:'Immeuble',immeuble_rapport:'Immeuble de rapport',parking:'Parking',box:'Box',garage:'Garage',cave:'Cave',local_commercial:'Local commercial',autre:'Autre'}
const annexesLabels:Record<string,string>={cave:'Cave',parking:'Parking',box:'Box',garage:'Garage',cour:'Cour',jardin:'Jardin',grenier:'Grenier',terrasse:'Terrasse',balcon:'Balcon'}
export default async function BiensPage(){
 const supabase=await createClient(); const {data}=await supabase.from('biens').select('*').order('created_at',{ascending:false}); const liste=(data??[]) as Bien[]
 return <div className="p-6 max-w-5xl mx-auto"><div className="flex items-center justify-between mb-6"><div><h1 className="text-2xl font-bold text-slate-900">Mes biens</h1><p className="text-slate-500 text-sm mt-1">{liste.length} bien{liste.length!==1?'s':''} enregistré{liste.length!==1?'s':''}</p></div><Link href="/dashboard/biens/nouveau" className="bg-blue-600 text-white rounded-xl px-4 py-2 text-sm font-medium">+ Ajouter un bien</Link></div>
 {liste.length===0?<div className="bg-white rounded-2xl border p-12 text-center text-slate-500">Aucun bien pour le moment.</div>:<div className="grid gap-4 sm:grid-cols-2">{liste.map(b=>{const immeuble=b.type==='immeuble'||b.type==='immeuble_rapport';return <div key={b.id} className="relative bg-white rounded-2xl border border-slate-100 shadow-sm hover:shadow-md transition-shadow"><Link href={`/dashboard/biens/${b.id}`} className="block p-5 pb-16"><div className="flex justify-between gap-3 mb-3"><h3 className="font-semibold text-slate-900">{b.nom}</h3><span className="text-xs bg-slate-100 text-slate-600 rounded-full px-2 py-1 h-fit">{labels[b.type]??b.type}</span></div><p className="text-sm text-slate-500 mb-3">{b.adresse}, {b.code_postal} {b.ville}</p><div className="flex flex-wrap gap-4 text-sm text-slate-600">{(immeuble?b.surface_totale_m2:b.surface_m2)!=null&&<span>{immeuble?b.surface_totale_m2:b.surface_m2} m²</span>}{immeuble&&b.nb_lots!=null&&<span>{b.nb_lots} lots</span>}{!immeuble&&b.nb_pieces!=null&&<span>{b.nb_pieces} pièce{b.nb_pieces!==1?'s':''}</span>}{b.prix_achat!=null&&<span>{Number(b.prix_achat).toLocaleString('fr-FR')} €</span>}</div>{b.annexes?.length>0&&<div className="flex flex-wrap gap-1 mt-3">{b.annexes.map(a=><span key={a} className="text-xs bg-slate-100 text-slate-500 px-2 py-0.5 rounded-full">{annexesLabels[a]??a}</span>)}</div>}<p className="text-xs text-blue-600 mt-4">Consulter le bien →</p></Link><div className="absolute bottom-4 right-4 flex gap-2"><Link href={`/dashboard/biens/${b.id}/modifier`} className="text-xs font-medium text-blue-600 border border-blue-200 rounded-lg px-2.5 py-1.5 bg-white">Modifier</Link><DeleteBienButton id={b.id} nom={b.nom}/></div></div>})}</div>}</div>
}