'use client'
import {useEffect,useState} from 'react'
import {useRouter} from 'next/navigation'
import Link from 'next/link'
import {createClient} from '@/lib/supabase/client'

export default function ModifierBailPage({params}:{params:Promise<{id:string}>}){
  const router=useRouter()
  const[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null),[id,setId]=useState(''),[bailId,setBailId]=useState('')
  const[form,setForm]=useState({date_entree:'',date_sortie:'',duree_bail_ans:'',mode_paiement:'',loyer_hc:'',charges:'',caution:'',caution_payee:false,actif:true,commentaire:''})
  useEffect(()=>{params.then(async({id})=>{setId(id);const s=createClient();const{data:loc}=await s.from('locataires').select('bail_id').eq('id',id).single();if(!loc?.bail_id){setError('Aucun bail commun n’est rattaché à cet occupant.');setLoading(false);return}const{data:bail,error:e}=await s.from('baux').select('*').eq('id',loc.bail_id).single();if(e||!bail){setError(e?.message??'Bail introuvable.');setLoading(false);return}setBailId(bail.id);setForm({date_entree:bail.date_entree??'',date_sortie:bail.date_sortie??'',duree_bail_ans:bail.duree_bail_ans?.toString()??'',mode_paiement:bail.mode_paiement??'',loyer_hc:bail.loyer_hc?.toString()??'',charges:bail.charges?.toString()??'',caution:bail.caution?.toString()??'',caution_payee:bail.caution_payee??false,actif:bail.actif??true,commentaire:bail.commentaire??''});setLoading(false)})},[params])
  function ch(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement>){const{name,value,type}=e.target;setForm(p=>({...p,[name]:type==='checkbox'?(e.target as HTMLInputElement).checked:value}))}
  async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setError(null);const s=createClient();const{error:e1}=await s.from('baux').update({date_entree:form.date_entree,date_sortie:form.date_sortie||null,duree_bail_ans:form.duree_bail_ans?Number(form.duree_bail_ans):null,mode_paiement:form.mode_paiement||null,loyer_hc:Number(form.loyer_hc||0),charges:Number(form.charges||0),caution:Number(form.caution||0),caution_payee:form.caution_payee,actif:form.actif,commentaire:form.commentaire||null}).eq('id',bailId);if(e1){setError(e1.message);setSaving(false);return}router.push(`/dashboard/locataires/${id}`);router.refresh()}
  if(loading)return <div className="p-6">Chargement…</div>
  const cls='w-full border border-slate-200 rounded-xl px-3 py-2 text-sm'
  return <div className="p-4 sm:p-6 max-w-2xl mx-auto"><div className="flex items-center gap-3 mb-6"><Link href={`/dashboard/locataires/${id}`} className="text-slate-400">←</Link><div><h1 className="text-2xl font-bold">Modifier le bail</h1><p className="text-sm text-slate-500 mt-1">Modifiez ici uniquement les informations communes au bail. Les informations propres à chaque occupant se modifient depuis sa fiche.</p></div></div>{error&&!bailId?<div className="bg-white rounded-2xl border p-5 text-sm text-red-600">{error}</div>:<form onSubmit={submit} className="bg-white rounded-2xl border p-4 sm:p-6 space-y-5"><Sec t="Bail"><div className="grid sm:grid-cols-2 gap-3"><Field l="Début du bail *"><input name="date_entree" type="date" value={form.date_entree} onChange={ch} required className={cls}/></Field><Field l="Fin du bail"><input name="date_sortie" type="date" value={form.date_sortie} onChange={ch} className={cls}/></Field><Field l="Durée du bail (ans)"><input name="duree_bail_ans" type="number" min="0" step="1" value={form.duree_bail_ans} onChange={ch} className={cls}/></Field><Field l="Mode de paiement"><input name="mode_paiement" value={form.mode_paiement} onChange={ch} className={cls}/></Field></div><label className="flex gap-2 text-sm"><input type="checkbox" name="actif" checked={form.actif} onChange={ch}/>Bail en cours</label></Sec><Sec t="Finances du bail"><div className="grid sm:grid-cols-3 gap-3"><Field l="Loyer HC (€) *"><input name="loyer_hc" type="number" min="0" step="0.01" value={form.loyer_hc} onChange={ch} required className={cls}/></Field><Field l="Charges (€) *"><input name="charges" type="number" min="0" step="0.01" value={form.charges} onChange={ch} required className={cls}/></Field><Field l="Caution (€)"><input name="caution" type="number" min="0" step="0.01" value={form.caution} onChange={ch} className={cls}/></Field></div><label className="flex gap-2 text-sm"><input type="checkbox" name="caution_payee" checked={form.caution_payee} onChange={ch}/>Caution reçue</label></Sec><Sec t="Commentaire"><textarea name="commentaire" value={form.commentaire} onChange={ch} rows={4} className={cls}/></Sec>{error&&<p className="text-sm text-red-600">{error}</p>}<div className="flex gap-3"><Link href={`/dashboard/locataires/${id}`} className="flex-1 text-center border rounded-xl py-2.5 text-sm">Annuler</Link><button disabled={saving} className="flex-1 bg-blue-600 text-white rounded-xl py-2.5 text-sm font-medium disabled:opacity-60">{saving?'Enregistrement…':'Enregistrer les modifications'}</button></div></form>}</div>
}
function Sec({t,children}:{t:string;children:React.ReactNode}){return <section className="space-y-3"><p className="text-xs font-semibold text-slate-400 uppercase tracking-wide">{t}</p>{children}</section>}
function Field({l,children}:{l:string;children:React.ReactNode}){return <label className="block"><span className="block text-sm font-medium text-slate-700 mb-1">{l}</span>{children}</label>}
