'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {useRouter} from 'next/navigation'
import {createClient} from '@/lib/supabase/client'

export default function AjouterOccupant({params}:{params:Promise<{id:string}>}){
 const router=useRouter(),[id,setId]=useState(''),[bailId,setBailId]=useState(''),[bail,setBail]=useState<any>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null),[form,setForm]=useState({civilite:'',nom_famille:'',prenom:'',email:'',telephone:'',date_entree:''})
 useEffect(()=>{params.then(async({id})=>{setId(id);const s=createClient();const{data:loc}=await s.from('locataires').select('*').eq('id',id).single();if(!loc?.bail_id){setError('Aucun bail actif n’est rattaché à ce locataire.');setLoading(false);return}const{data:b}=await s.from('baux').select('*').eq('id',loc.bail_id).single();if(!b){setError('Bail introuvable.');setLoading(false);return}setBailId(loc.bail_id);setBail(b);setForm(p=>({...p,date_entree:new Date().toISOString().slice(0,10)}));setLoading(false)})},[params])
 function ch(e:React.ChangeEvent<HTMLInputElement|HTMLSelectElement>){setForm(p=>({...p,[e.target.name]:e.target.value}))}
 async function submit(e:React.FormEvent){e.preventDefault();if(!bail)return;setSaving(true);setError(null);const s=createClient();if(form.date_entree<bail.date_entree){setError(`La date d’entrée de ce nouvel occupant ne peut pas être antérieure au début du bail (${new Date(bail.date_entree+'T00:00:00').toLocaleDateString('fr-FR')}).`);setSaving(false);return}
 const{data:{user}}=await s.auth.getUser();if(!user){setError('Session expirée.');setSaving(false);return}
 const nomComplet=`${form.prenom.trim()} ${form.nom_famille.trim()}`.trim();const payload={proprietaire_id:user.id,bien_id:bail.bien_id,bail_id:bailId,est_principal:false,civilite:form.civilite||null,nom_famille:form.nom_famille.trim(),prenom:form.prenom.trim(),nom:nomComplet,email:form.email.trim(),telephone:form.telephone.trim()||null,date_entree:form.date_entree,loyer_hc:bail.loyer_hc,charges:bail.charges,caution:bail.caution,caution_payee:bail.caution_payee,duree_bail_ans:bail.duree_bail_ans,echeance_bail:bail.echeance_bail,mode_paiement:bail.mode_paiement,commentaire:null,actif:true}
 const{error:ie}=await s.from('locataires').insert(payload);if(ie){setError(ie.message);setSaving(false);return}if(bail.type_occupation==='individuel'){const{error:be}=await s.from('baux').update({type_occupation:'bail_commun'}).eq('id',bailId);if(be){setError(be.message);setSaving(false);return}}
 router.push(`/dashboard/locataires/${id}`);router.refresh()}
 if(loading)return <div className="p-6">Chargement…</div>;const cls='w-full rounded-xl border border-slate-200 px-3 py-2 text-sm';return <div className="p-4 sm:p-6 max-w-2xl mx-auto"><Link href={`/dashboard/locataires/${id}`} className="text-sm text-slate-500">← Retour au bail</Link><h1 className="text-2xl font-bold mt-5">Ajouter un occupant au bail</h1><p className="text-sm text-slate-500 mt-1 mb-6">Le bail conserve sa date d’origine. Le nouvel occupant possède sa propre date d’entrée.</p>{error&&<div className="bg-red-50 text-red-700 rounded-xl p-3 text-sm mb-4">{error}</div>}{bail&&<form onSubmit={submit} className="bg-white border rounded-2xl p-5 sm:p-6 space-y-4"><div className="grid sm:grid-cols-3 gap-3"><Field l="Civilité *"><select name="civilite" value={form.civilite} onChange={ch} required className={cls}><option value="">Choisir…</option><option value="M.">M.</option><option value="Mme">Mme</option></select></Field><Field l="Nom *"><input name="nom_famille" value={form.nom_famille} onChange={ch} required className={cls}/></Field><Field l="Prénom *"><input name="prenom" value={form.prenom} onChange={ch} required className={cls}/></Field></div><Field l="Email *"><input name="email" type="email" value={form.email} onChange={ch} required className={cls}/></Field><Field l="Téléphone"><input name="telephone" value={form.telephone} onChange={ch} className={cls}/></Field><Field l="Date d’entrée dans le bail *"><input name="date_entree" type="date" min={bail.date_entree} value={form.date_entree} onChange={ch} required className={cls}/></Field><div className="rounded-xl bg-blue-50 p-3 text-xs text-blue-700">Début du bail : {new Date(bail.date_entree+'T00:00:00').toLocaleDateString('fr-FR')}. L’ajout de cet occupant ne modifiera pas cette date.</div><div className="flex gap-3 pt-2"><Link href={`/dashboard/locataires/${id}`} className="flex-1 text-center border rounded-xl py-2.5 text-sm">Annuler</Link><button disabled={saving} className="flex-1 bg-blue-600 text-white rounded-xl py-2.5 text-sm font-medium disabled:opacity-60">{saving?'Ajout…':'Ajouter au bail'}</button></div></form>}</div>}
function Field({l,children}:{l:string;children:React.ReactNode}){return <label className="block"><span className="block text-sm font-medium text-slate-700 mb-1">{l}</span>{children}</label>}
