import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { generateQuittancePdf, cleanPdfText, MOIS_FR } from '@/lib/generateQuittancePdf'
function formatDate(d:Date){return `${String(d.getDate()).padStart(2,'0')} ${MOIS_FR[d.getMonth()]} ${d.getFullYear()}`}
function formatType(value:string){return cleanPdfText(value||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function formatReference(mois:string){const[y,m]=String(mois||'').split('-');return m&&y?`${m}.${y}`:String(mois||'')}
function formatIdentite(civilite?:string|null,nom?:string|null,prenom?:string|null,fallback?:string|null){const identite=[civilite,nom?.toUpperCase(),prenom].filter(Boolean).join(' ').trim();return identite||cleanPdfText(fallback||'-')}
export async function GET(req:NextRequest){try{
 const id=req.nextUrl.searchParams.get('id');if(!id)return NextResponse.json({error:'Quittance manquante'},{status:400});const supabase=await createClient();const{data:{user},error:ae}=await supabase.auth.getUser();if(ae||!user)return NextResponse.json({error:'Non autorisé'},{status:401})
 const{data:q,error}=await supabase.from('quittances').select('*, locataires(nom,nom_famille,prenom,civilite,email,bail_id,mode_paiement), biens(nom,adresse,ville,type)').eq('id',id).eq('proprietaire_id',user.id).single();if(error||!q)return NextResponse.json({error:'Quittance introuvable'},{status:404})
 const{data:profile}=await supabase.from('profiles').select('nom,prenom,civilite,telephone,signature_base64,iban,bic').eq('id',user.id).single();const pn=formatIdentite(profile?.civilite,profile?.nom,profile?.prenom,user.email);let detailCharges:string[]=[];let lot:any=null;let modeBail=q.locataires?.mode_paiement??'';if(q.locataires?.bail_id){const{data:b}=await supabase.from('baux').select('lot_id,mode_paiement,detail_charges').eq('id',q.locataires.bail_id).eq('proprietaire_id',user.id).maybeSingle();modeBail=b?.mode_paiement||modeBail;detailCharges=Array.isArray(b?.detail_charges)?b.detail_charges:[];if(b?.lot_id){const r=await supabase.from('lots').select('numero_lot,nom_personnalise,type,specificite,surface_m2').eq('id',b.lot_id).maybeSingle();lot=r.data}}
 const{data:pays}=await supabase.from('paiements').select('commentaire,mode_paiement,statut').eq('proprietaire_id',user.id).eq('locataire_id',q.locataire_id).eq('mois',q.mois);const modes=Array.from(new Set((pays??[]).filter((p:any)=>['recu','partiel'].includes(p.statut)).map((p:any)=>p.mode_paiement?.trim()).filter(Boolean))) as string[];const modePaiement=(modes.length?modes:[modeBail]).filter(Boolean).map(m=>({virement:'Virement',prelevement:'Prélèvement',cheque:'Chèque',especes:'Espèces'} as Record<string,string>)[m]||formatType(m)).join(' / ');const commentaire=(pays??[]).map((p:any)=>cleanPdfText(p.commentaire||'')).filter(Boolean).join(' · ');const ref=formatReference(q.mois)
 const typeAffiche=lot?.nom_personnalise?cleanPdfText(lot.nom_personnalise):formatType(lot?.type??q.biens?.type??'');const locataireNom=formatIdentite(q.locataires?.civilite,q.locataires?.nom_famille,q.locataires?.prenom,q.locataires?.nom)
 const annexeDetails=Array.isArray(q.lots_annexes_detail)?q.lots_annexes_detail:[];const annexeIds=annexeDetails.map((a:any)=>a.lot_id).filter(Boolean);const {data:annexeLots}=annexeIds.length?await supabase.from('lots').select('id,nom_personnalise,numero_lot').in('id',annexeIds).eq('proprietaire_id',user.id):{data:[]};const annexes=annexeDetails.map((a:any)=>{const lot=(annexeLots??[]).find((l:any)=>l.id===a.lot_id);return{nom:cleanPdfText(a.nom_personnalise?.trim()||lot?.nom_personnalise?.trim()||a.numero_lot||lot?.numero_lot||'Annexe'),montant:Number(a.prix_mensuel??0)}});
 const bytes=await generateQuittancePdf({locataireNom:cleanPdfText(locataireNom),locataireEmail:cleanPdfText(q.locataires?.email??''),proprietaireNom:cleanPdfText(pn),proprietaireEmail:cleanPdfText(user.email??''),proprietaireTelephone:cleanPdfText(profile?.telephone??''),bienNom:cleanPdfText(q.biens?.nom??''),bienAdresse:cleanPdfText(q.biens?.adresse??''),bienVille:cleanPdfText(q.biens?.ville??''),lotNom:cleanPdfText(lot?.numero_lot??''),typeLogement:typeAffiche,specificiteLogement:cleanPdfText(lot?.specificite??''),surface:lot?.surface_m2,mois:q.mois,reference:ref,loyerHc:Number(q.loyer_hc??0),charges:Number(q.charges??0),detailCharges,solde:Number(q.solde??0),total:Number(q.total??0),modePaiement:cleanPdfText(modePaiement),annexes,fraisAnnexes:Number(q.lots_annexes_total??0),commentaire,iban:cleanPdfText(profile?.iban??''),bic:cleanPdfText(profile?.bic??''),signatureDataUrl:profile?.signature_base64??'',dateSignature:formatDate(q.date_signature?new Date(q.date_signature):new Date())})
 const name=`quittance-${q.mois}-${String(q.locataires?.nom??'locataire').toLowerCase().replace(/\s+/g,'-')}.pdf`;return new NextResponse(Buffer.from(bytes),{status:200,headers:{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="${name}"`,'Cache-Control':'private, no-store'}})
}catch(e){console.error('quittance-pdf error:',e);return NextResponse.json({error:'Erreur lors de la génération du PDF'},{status:500})}}
