import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { generateQuittancePdf, cleanPdfText, MOIS_FR } from '@/lib/generateQuittancePdf'
function formatDate(d:Date){return `${String(d.getDate()).padStart(2,'0')} ${MOIS_FR[d.getMonth()]} ${d.getFullYear()}`}
export async function GET(req:NextRequest){try{
 const id=req.nextUrl.searchParams.get('id');if(!id)return NextResponse.json({error:'Quittance manquante'},{status:400});const supabase=await createClient();const{data:{user},error:ae}=await supabase.auth.getUser();if(ae||!user)return NextResponse.json({error:'Non autorisé'},{status:401})
 const{data:q,error}=await supabase.from('quittances').select('*, locataires(nom,email,bail_id), biens(nom,adresse,ville,type)').eq('id',id).eq('proprietaire_id',user.id).single();if(error||!q)return NextResponse.json({error:'Quittance introuvable'},{status:404})
 const{data:profile}=await supabase.from('profiles').select('nom,prenom,telephone,signature_base64,iban,bic').eq('id',user.id).single();const pn=`${profile?.prenom??''} ${profile?.nom??''}`.trim()||user.email||'-';let lot:any=null;if(q.locataires?.bail_id){const{data:b}=await supabase.from('baux').select('lot_id').eq('id',q.locataires.bail_id).eq('proprietaire_id',user.id).maybeSingle();if(b?.lot_id){const r=await supabase.from('lots').select('numero_lot,type,specificite,surface').eq('id',b.lot_id).maybeSingle();lot=r.data}}
 const{data:pays}=await supabase.from('paiements').select('commentaire,mode_paiement').eq('proprietaire_id',user.id).eq('locataire_id',q.locataire_id).eq('mois',q.mois);const commentaire=(pays??[]).map((p:any)=>cleanPdfText(p.commentaire||'')).filter(Boolean).join(' · ');const mode=(pays??[]).map((p:any)=>p.mode_paiement).find(Boolean)||'';const ref=`EKO-${String(q.mois||'').replace('-','')}-${String(q.id).slice(0,6).toUpperCase()}`
 const bytes=await generateQuittancePdf({locataireNom:cleanPdfText(q.locataires?.nom??'-'),locataireEmail:cleanPdfText(q.locataires?.email??''),proprietaireNom:cleanPdfText(pn),proprietaireEmail:cleanPdfText(user.email??''),proprietaireTelephone:cleanPdfText(profile?.telephone??''),bienNom:cleanPdfText(q.biens?.nom??''),bienAdresse:cleanPdfText(q.biens?.adresse??''),bienVille:cleanPdfText(q.biens?.ville??''),lotNom:cleanPdfText(lot?.numero_lot??''),typeLogement:cleanPdfText(lot?.type??q.biens?.type??''),specificiteLogement:cleanPdfText(lot?.specificite??''),surface:lot?.surface,mois:q.mois,reference:ref,loyerHc:Number(q.loyer_hc??0),charges:Number(q.charges??0),solde:Number(q.solde??0),total:Number(q.total??0),modePaiement:cleanPdfText(mode),commentaire,iban:cleanPdfText(profile?.iban??''),bic:cleanPdfText(profile?.bic??''),signatureDataUrl:profile?.signature_base64??'',dateSignature:formatDate(q.date_signature?new Date(q.date_signature):new Date())})
 const name=`quittance-${q.mois}-${String(q.locataires?.nom??'locataire').toLowerCase().replace(/\s+/g,'-')}.pdf`;return new NextResponse(Buffer.from(bytes),{status:200,headers:{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="${name}"`,'Cache-Control':'private, no-store'}})
}catch(e){console.error('quittance-pdf error:',e);return NextResponse.json({error:'Erreur lors de la génération du PDF'},{status:500})}}
