'use client'

import { useEffect,useMemo,useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'

type Document={id:string;bien_id:string|null;lot_id:string|null;categorie:string;nom:string;date_document:string|null;fichier_url:string|null;commentaire:string|null;created_at:string}
type Quittance={id:string;bien_id:string;locataire_id:string;mois:string;total:number;envoyee:boolean;date_signature:string|null}
type Bien={id:string;nom:string;ville:string};type Lot={id:string;bien_id:string;numero_lot:string|null;nom_personnalise:string|null;type:string};type Locataire={id:string;nom:string;bien_id:string;bail_id:string|null};type Bail={id:string;lot_id:string|null}
type Item={id:string;source:'document'|'quittance';bien_id:string|null;lot_id:string|null;categorie:string;nom:string;date:string;detail:string;href:string|null}
const cats:Record<string,string>={administratif:'Administratif / impôts et taxes',contrat_bail:'Contrats / Baux',etat_des_lieux:'États des lieux',quittance:'Quittances',facture_devis:'Factures et devis',entretien:'Entretien',travaux:'Travaux'}
const fmt=(d:string)=>new Date(`${d.slice(0,10)}T00:00:00`).toLocaleDateString('fr-FR',{day:'2-digit',month:'short',year:'numeric'})
const lotLabel=(l:Lot)=>l.nom_personnalise?.trim()||l.numero_lot||l.type
export default function DocumentsPage(){const [loading,setLoading]=useState(true),[opening,setOpening]=useState<string|null>(null),[docs,setDocs]=useState<Document[]>([]),[qs,setQs]=useState<Quittance[]>([]),[biens,setBiens]=useState<Bien[]>([]),[lots,setLots]=useState<Lot[]>([]),[locs,setLocs]=useState<Locataire[]>([]),[baux,setBaux]=useState<Bail[]>([]),[bien,setBien]=useState('all'),[lot,setLot]=useState('all'),[cat,setCat]=useState('all'),[dateFrom,setDateFrom]=useState(''),[dateTo,setDateTo]=useState('');useEffect(()=>{const s=createClient();Promise.all([s.from('documents').select('*').order('date_document',{ascending:false}),s.from('quittances').select('id,bien_id,locataire_id,mois,total,envoyee,date_signature').order('mois',{ascending:false}),s.from('biens').select('id,nom,ville').order('nom'),s.from('lots').select('id,bien_id,numero_lot,nom_personnalise,type').order('numero_lot'),s.from('locataires').select('id,nom,bien_id,bail_id'),s.from('baux').select('id,lot_id')]).then(r=>{setDocs((r[0].data??[]) as Document[]);setQs((r[1].data??[]) as Quittance[]);setBiens((r[2].data??[]) as Bien[]);setLots((r[3].data??[]) as Lot[]);setLocs((r[4].data??[]) as Locataire[]);setBaux((r[5].data??[]) as Bail[]);setLoading(false)})},[]);const locMap=new Map(locs.map(l=>[l.id,l])),bailMap=new Map(baux.map(b=>[b.id,b])),bienMap=new Map(biens.map(b=>[b.id,b])),lotMap=new Map(lots.map(l=>[l.id,l]));const items=useMemo<Item[]>(()=>[...docs.map(d=>({id:d.id,source:'document' as const,bien_id:d.bien_id,lot_id:d.lot_id,categorie:d.categorie,nom:d.nom,date:(d.date_document||d.created_at).slice(0,10),detail:d.commentaire||'',href:d.fichier_url})),...qs.map(q=>{const l=locMap.get(q.locataire_id),b=l?.bail_id?bailMap.get(l.bail_id):undefined;return{id:q.id,source:'quittance' as const,bien_id:q.bien_id||l?.bien_id||null,lot_id:b?.lot_id??null,categorie:'quittance',nom:`Quittance — ${l?.nom??'Locataire'}`,date:`${q.mois}-01`,detail:`${Number(q.total).toLocaleString('fr-FR')} € · ${q.envoyee?'Envoyée':'À envoyer'}`,href:`/dashboard/signatures/${q.id}`}})].sort((a,b)=>b.date.localeCompare(a.date)),[docs,qs,locs,baux]);const availableLots=lots.filter(l=>bien==='all'||l.bien_id===bien),filtered=items.filter(i=>(bien==='all'||i.bien_id===bien)&&(lot==='all'||i.lot_id===lot)&&(cat==='all'||i.categorie===cat)&&(!dateFrom||i.date>=dateFrom)&&(!dateTo||i.date<=dateTo));async function openDocument(i:Item){if(!i.href)return;if(i.source==='quittance'||i.href.startsWith('/'))return;setOpening(i.id);const s=createClient(),{data,error}=await s.storage.from('documents').createSignedUrl(i.href,60);setOpening(null);if(error||!data?.signedUrl){alert('Impossible d’ouvrir ce document.');return}window.open(data.signedUrl,'_blank','noopener,noreferrer')}
return <div className="p-6 max-w-6xl mx-auto"><div className="flex flex-wrap items-center justify-between gap-4 mb-6"><div><h1 className="text-2xl font-bold text-slate-900">Documents</h1><p className="text-sm text-slate-500 mt-1">Centralisez vos documents et retrouvez-les par bien, catégorie et période.</p></div><Link href="/dashboard/signatures/nouveau" className="bg-blue-600 text-white rounded-xl px-4 py-2 text-sm font-medium hover:bg-blue-700">+ Ajouter un document</Link></div><div className="bg-white border rounded-2xl p-4 mb-5"><div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3"><Sel label="Bien" value={bien} set={v=>{setBien(v);setLot('all')}}><option value="all">Tous les biens</option>{biens.map(b=><option key={b.id} value={b.id}>{b.nom}</option>)}</Sel><Sel label="Lot" value={lot} set={setLot}><option value="all">Tous les lots</option>{availableLots.map(l=><option key={l.id} value={l.id}>{lotLabel(l)}</option>)}</Sel><Sel label="Catégorie" value={cat} set={setCat}><option value="all">Toutes les catégories</option>{Object.entries(cats).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Sel><DateField label="Du" value={dateFrom} set={setDateFrom}/><DateField label="Au" value={dateTo} set={setDateTo}/></div><button onClick={()=>{setBien('all');setLot('all');setCat('all');setDateFrom('');setDateTo('')}} className="mt-3 text-xs text-blue-600 hover:underline">Réinitialiser les filtres</button></div>{loading?<div className="h-40 rounded-2xl bg-slate-100 animate-pulse"/>:filtered.length===0?<div className="bg-white border rounded-2xl p-12 text-center"><p className="text-sm text-slate-500">Aucun document pour ces critères.</p></div>:<div className="bg-white border rounded-2xl divide-y overflow-hidden">{filtered.map(i=>{const b=i.bien_id?bienMap.get(i.bien_id):null,l=i.lot_id?lotMap.get(i.lot_id):null;return <div key={`${i.source}-${i.id}`} className="px-5 py-4 flex items-center justify-between gap-4 hover:bg-slate-50"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-medium text-sm text-slate-900 truncate">{i.nom}</p><span className="text-[11px] px-2 py-0.5 rounded-full bg-slate-100 text-slate-600">{cats[i.categorie]??i.categorie}</span></div><p className="text-xs text-slate-400 mt-1">{b?`${b.nom}${b.ville?` · ${b.ville}`:''}`:'Non rattaché'}{l?` · ${lotLabel(l)}`:''}{i.detail?` · ${i.detail}`:''}</p></div><div className="flex items-center gap-3 shrink-0"><span className="text-xs text-slate-400">{fmt(i.date)}</span>{i.href&&(i.source==='quittance'?<Link href={i.href} className="text-xs text-blue-600 hover:underline">Ouvrir</Link>:<button onClick={()=>openDocument(i)} disabled={opening===i.id} className="text-xs text-blue-600 hover:underline disabled:opacity-50">{opening===i.id?'Ouverture…':'Ouvrir'}</button>)}</div></div>})}</div>}</div>}
function Sel({label,value,set,children}:{label:string;value:string;set:(v:string)=>void;children:React.ReactNode}){return <label className="text-xs text-slate-500"><span className="block mb-1">{label}</span><select value={value} onChange={e=>set(e.target.value)} className="w-full border rounded-lg px-3 py-2 bg-white text-sm text-slate-700 outline-none focus:ring-2 focus:ring-blue-100">{children}</select></label>}
function DateField({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="text-xs text-slate-500"><span className="block mb-1">{label}</span><input type="date" value={value} onChange={e=>set(e.target.value)} className="w-full border rounded-lg px-3 py-2 bg-white text-sm text-slate-700 outline-none focus:ring-2 focus:ring-blue-100"/></label>}
