'use client'

import { useEffect,useMemo,useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'

type Bien={id:string;nom:string;ville:string;type:string;prix_achat:number|null;date_acquisition:string|null;date_mise_location:string|null}
type Lot={id:string;bien_id:string;type:string}
type Bail={id:string;bien_id:string;lot_id:string|null;date_entree:string;date_sortie:string|null;loyer_hc:number;actif:boolean}
type Quittance={id:string;bien_id:string;locataire_id:string;mois:string;total:number;envoyee:boolean}
type Paiement={id:string;bien_id:string|null;locataire_id:string;mois:string;montant:number;statut:string;date_paiement:string|null}
type Depense={bien_id:string|null;categorie:string;type_travaux:string|null;montant:number;date_depense:string}
type Financement={bien_id:string;mensualite:number|null;assurance_mensuelle:number|null}
type Locataire={id:string;nom:string}
type Monthly={label:string;recettes:number;depenses:number;cash:number;charges:number}
const HAB_BIEN=new Set(['appartement','maison','studio']),HAB_LOT=new Set(['appartement','studio','maison']),HORS=new Set(['parking','box','garage','cave','local_commercial','local-commercial','local commercial']),DAY=86400000
const OPERATING_CHARGE_CATEGORIES=new Set(['charges','assurance','gestion','taxe'])
const n=(v:number|null|undefined)=>Number(v??0),euro=(v:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(v),iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,ds=(s:string)=>new Date(`${s}T00:00:00`),days=(a:Date,b:Date)=>Math.max(0,Math.floor((b.getTime()-a.getTime())/DAY)+1)
function isOperatingCharge(d:Depense){return OPERATING_CHARGE_CATEGORIES.has(d.categorie)||(d.categorie==='travaux'&&d.type_travaux==='Entretien / réparation')}
function vacancy(bien:Bien,lotId:string|null,baux:Bail[],start:Date,end:Date){const relevant=baux.filter(b=>b.bien_id===bien.id&&(lotId?b.lot_id===lotId:!b.lot_id)),available=bien.date_mise_location?ds(bien.date_mise_location):null;if(!available)return null;const s=available>start?available:start;if(s>end)return null;const den=days(s,end),intervals=relevant.map(b=>({s:ds(b.date_entree),e:b.date_sortie?ds(b.date_sortie):end})).map(x=>({s:x.s<s?s:x.s,e:x.e>end?end:x.e})).filter(x=>x.s<=x.e).sort((a,b)=>a.s.getTime()-b.s.getTime());let occ=0,last:Date|null=null;for(const x of intervals){const ns=last&&x.s<=new Date(last.getTime()+DAY)?new Date(last.getTime()+DAY):x.s;if(ns<=x.e)occ+=days(ns,x.e);if(!last||x.e>last)last=x.e}return Math.max(0,Math.min(100,(den-occ)/den*100))}
function monthKey(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function monthKeys(start:Date,end:Date){const out:string[]=[];for(let d=new Date(start.getFullYear(),start.getMonth(),1);d<=end;d=new Date(d.getFullYear(),d.getMonth()+1,1))out.push(monthKey(d));return out}
function fmtMonth(m:string){const[y,mo]=m.split('-');return new Date(+y,+mo-1,1).toLocaleDateString('fr-FR',{month:'short',year:'2-digit'}).replace(/^./,c=>c.toUpperCase())}
function shiftDays(d:Date,count:number){return new Date(d.getTime()+count*DAY)}
export default function DashboardPage(){
 const now=new Date(),[loading,setLoading]=useState(true),[from,setFrom]=useState(`${now.getFullYear()}-01-01`),[to,setTo]=useState(iso(now)),[biens,setBiens]=useState<Bien[]>([]),[lots,setLots]=useState<Lot[]>([]),[baux,setBaux]=useState<Bail[]>([]),[qs,setQs]=useState<Quittance[]>([]),[pays,setPays]=useState<Paiement[]>([]),[deps,setDeps]=useState<Depense[]>([]),[fins,setFins]=useState<Financement[]>([]),[locs,setLocs]=useState<Locataire[]>([])
 useEffect(()=>{const s=createClient();Promise.all([s.from('biens').select('id,nom,ville,type,prix_achat,date_acquisition,date_mise_location'),s.from('lots').select('id,bien_id,type'),s.from('baux').select('id,bien_id,lot_id,date_entree,date_sortie,loyer_hc,actif'),s.from('quittances').select('id,bien_id,locataire_id,mois,total,envoyee').order('mois',{ascending:false}),s.from('paiements').select('id,bien_id,locataire_id,mois,montant,statut,date_paiement'),s.from('depenses').select('bien_id,categorie,type_travaux,montant,date_depense'),s.from('financements').select('bien_id,mensualite,assurance_mensuelle'),s.from('locataires').select('id,nom')]).then(r=>{setBiens((r[0].data??[]) as Bien[]);setLots((r[1].data??[]) as Lot[]);setBaux((r[2].data??[]) as Bail[]);setQs((r[3].data??[]) as Quittance[]);setPays((r[4].data??[]) as Paiement[]);setDeps((r[5].data??[]) as Depense[]);setFins((r[6].data??[]) as Financement[]);setLocs((r[7].data??[]) as Locataire[]);setLoading(false)})},[])
 const start=ds(from),end=ds(to),valid=start<=end
 function preset(months:number|'year'){const e=new Date();setTo(iso(e));if(months==='year')setFrom(`${e.getFullYear()}-01-01`);else{const s=new Date(e);s.setMonth(s.getMonth()-months);s.setDate(s.getDate()+1);setFrom(iso(s))}}
 const calc=useMemo(()=>{if(!valid)return{recettes:0,depenses:0,charges:0,chargesEvolution:null as number|null,vacance:null as number|null,rendement:null as number|null,marge:0,cash:0,net:null as number|null,monthly:[] as Monthly[]};const keys=monthKeys(start,end),received=pays.filter(p=>['recu','partiel'].includes(p.statut)&&p.date_paiement&&ds(p.date_paiement)>=start&&ds(p.date_paiement)<=end),dIn=deps.filter(d=>d.date_depense&&ds(d.date_depense)>=start&&ds(d.date_depense)<=end),recettes=received.reduce((a,p)=>a+n(p.montant),0),depenses=dIn.reduce((a,d)=>a+n(d.montant),0),charges=dIn.filter(isOperatingCharge).reduce((a,d)=>a+n(d.montant),0),periodDays=days(start,end),prevEnd=shiftDays(start,-1),prevStart=shiftDays(prevEnd,-periodDays+1),prevCharges=deps.filter(d=>isOperatingCharge(d)&&d.date_depense&&ds(d.date_depense)>=prevStart&&ds(d.date_depense)<=prevEnd).reduce((a,d)=>a+n(d.montant),0),chargesEvolution=prevCharges>0?(charges-prevCharges)/prevCharges*100:charges===0?0:null,vacs:number[]=[];biens.forEach(b=>{const bl=lots.filter(l=>l.bien_id===b.id&&HAB_LOT.has(l.type));(bl.length?bl.map(l=>l.id):HAB_BIEN.has(b.type)?[null]:[]).forEach(id=>{const v=vacancy(b,id,baux,start,end);if(v!==null)vacs.push(v)})});const vacance=vacs.length?vacs.reduce((a,b)=>a+b,0)/vacs.length:null,annual=baux.filter(b=>b.actif).reduce((a,b)=>a+n(b.loyer_hc)*12,0),prix=biens.reduce((a,b)=>a+n(b.prix_achat),0),rendement=prix>0?annual/prix*100:null,monthlyDebt=fins.reduce((a,f)=>a+n(f.mensualite)+n(f.assurance_mensuelle),0),marge=recettes-depenses,periodMonths=keys.length,cash=marge-monthlyDebt*periodMonths,net=recettes>0?cash/recettes*100:null,monthly=keys.map(key=>{const r=received.filter(p=>p.date_paiement?.startsWith(key)).reduce((a,p)=>a+n(p.montant),0),d=deps.filter(x=>x.date_depense?.startsWith(key)).reduce((a,x)=>a+n(x.montant),0),c=deps.filter(x=>isOperatingCharge(x)&&x.date_depense?.startsWith(key)).reduce((a,x)=>a+n(x.montant),0);return{label:fmtMonth(key),recettes:r,depenses:d,cash:r-d-monthlyDebt,charges:c}});return{recettes,depenses,charges,chargesEvolution,vacance,rendement,marge,cash,net,monthly}},[from,to,biens,lots,baux,pays,deps,fins,valid])
 const logements=biens.filter(b=>HAB_BIEN.has(b.type)).length+lots.filter(l=>HAB_LOT.has(l.type)).length,hors=biens.filter(b=>HORS.has(b.type)).length+lots.filter(l=>HORS.has(l.type)).length,locMap=new Map(locs.map(l=>[l.id,l.nom])),recent=qs.slice(0,5)
 const chargeSub=loading?'':calc.chargesEvolution===null?'Pas de période précédente comparable':`${calc.chargesEvolution>0?'+':''}${calc.chargesEvolution.toFixed(1)} % vs période précédente`
 return <div className="p-6 max-w-6xl mx-auto"><div className="flex flex-wrap items-end justify-between gap-4 mb-7"><div><h1 className="text-2xl font-bold text-slate-900">Tableau de bord</h1><p className="text-sm text-slate-500 mt-1">Pilotage patrimonial et financier</p></div><div><p className="text-xs text-slate-500 mb-1">Période</p><div className="flex flex-wrap items-center gap-2"><button onClick={()=>preset(3)} className="text-xs border rounded-lg px-2.5 py-2 bg-white">3 mois</button><button onClick={()=>preset(6)} className="text-xs border rounded-lg px-2.5 py-2 bg-white">6 mois</button><button onClick={()=>preset(12)} className="text-xs border rounded-lg px-2.5 py-2 bg-white">12 mois</button><button onClick={()=>preset('year')} className="text-xs border rounded-lg px-2.5 py-2 bg-white">Cette année</button><div className="flex items-center gap-1 border rounded-lg bg-white px-2"><input aria-label="Date de début" type="date" value={from} onChange={e=>setFrom(e.target.value)} className="py-1.5 text-xs outline-none"/><span className="text-slate-400">→</span><input aria-label="Date de fin" type="date" value={to} onChange={e=>setTo(e.target.value)} className="py-1.5 text-xs outline-none"/></div></div>{!valid&&<p className="text-xs text-red-600 mt-1">La date de début doit précéder la date de fin.</p>}</div></div>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 mb-7"><K l="Logements" v={loading?'…':String(logements)} href="/dashboard/biens"/><K l="Biens hors logements" v={loading?'…':String(hors)} href="/dashboard/biens"/><K l="Recettes encaissées" v={loading?'…':euro(calc.recettes)} href="/dashboard/paiements"/><K l="Dépenses" v={loading?'…':euro(calc.depenses)} href="/dashboard/depenses"/><K l="Charges" v={loading?'…':euro(calc.charges)} href="/dashboard/depenses" sub={chargeSub}/><K l="Taux de vacance" v={loading?'…':calc.vacance===null?'—':`${calc.vacance.toFixed(1)} %`} href="/dashboard/rentabilite"/><K l="Rentabilité brute annualisée" v={loading?'…':calc.rendement===null?'—':`${calc.rendement.toFixed(2)} %`} href="/dashboard/rentabilite"/><K l="Marge brute" v={loading?'…':euro(calc.marge)} href="/dashboard/rentabilite"/><K l="Cash-flow après dette" v={loading?'…':euro(calc.cash)} href="/dashboard/rentabilite"/><K l="Marge nette financière" v={loading?'…':calc.net===null?'—':`${calc.net.toFixed(1)} %`} href="/dashboard/rentabilite"/></div>
 <div className="grid lg:grid-cols-2 gap-5 mb-5"><Chart title="Encaissements et dépenses" data={calc.monthly} keys={['recettes','depenses']}/><Chart title="Cash-flow mensuel" data={calc.monthly} keys={['cash']}/></div>
 <div className="mb-8"><Chart title="Évolution des charges" data={calc.monthly} keys={['charges']}/></div>
 <div><div className="flex items-center justify-between mb-4"><div><h2 className="text-sm font-semibold text-slate-500 uppercase tracking-wide">Historique des quittances</h2><p className="text-xs text-slate-400 mt-1">Les dernières quittances restent accessibles avec leur statut.</p></div><Link href="/dashboard/quittances" className="text-xs text-blue-600 hover:underline">Voir tout →</Link></div>{loading?<div className="h-32 bg-slate-100 rounded-2xl animate-pulse"/>:recent.length===0?<div className="bg-white border rounded-2xl p-8 text-center text-sm text-slate-400">Aucune quittance</div>:<div className="bg-white rounded-2xl border divide-y">{recent.map(q=><Link key={q.id} href={`/dashboard/quittances/${q.id}`} className="flex justify-between items-center px-5 py-4 hover:bg-slate-50"><div><p className="font-medium text-sm">{locMap.get(q.locataire_id)??'—'}</p><p className="text-xs text-slate-400">{fmtMonth(q.mois)}</p></div><div className="flex items-center gap-3"><b className="text-sm">{euro(q.total)}</b><span className={`text-xs px-2 py-1 rounded-full ${q.envoyee?'bg-green-100 text-green-700':'bg-amber-100 text-amber-700'}`}>{q.envoyee?'Envoyée':'À envoyer'}</span></div></Link>)}</div>}</div><p className="mt-6 text-xs text-slate-400">Les recettes correspondent aux paiements réellement encaissés sur la période sélectionnée. Les charges regroupent les dépenses d’exploitation courante : charges, assurance, gestion, taxes et travaux d’entretien/réparation. Les autres travaux restent comptabilisés dans les dépenses sans alimenter le KPI Charges. L’évolution des charges est comparée à la période précédente de même durée. Le taux de vacance mesure les jours où un logement disponible à la location est resté sans bail, à partir de sa date de mise en location. La rentabilité brute est annualisée. Le cash-flow déduit les dépenses, les mensualités de crédit et l’assurance emprunteur ; la fiscalité n’est pas encore incluse.</p></div>
}
function K({l,v,href,sub}:{l:string;v:string;href:string;sub?:string}){return <Link href={href} className="bg-white border rounded-2xl p-5 hover:shadow-md transition-shadow"><p className="text-xs uppercase tracking-wide text-slate-500">{l}</p><p className="text-xl font-bold mt-1">{v}</p>{sub&&<p className="text-xs text-slate-400 mt-1">{sub}</p>}</Link>}
function Chart({title,data,keys}:{title:string;data:Monthly[];keys:('recettes'|'depenses'|'cash'|'charges')[]}){const W=620,H=240,L=55,R=18,T=18,B=42,vals=data.flatMap(d=>keys.map(k=>d[k]));let min=Math.min(0,...vals),max=Math.max(0,...vals);if(min===max){min-=1;max+=1}const y=(v:number)=>T+(max-v)/(max-min)*(H-T-B),x=(i:number)=>L+(data.length<=1?0:i*(W-L-R)/(data.length-1)),ticks=4,labels:{[k:string]:string}={recettes:'Encaissements',depenses:'Dépenses',cash:'Cash-flow',charges:'Charges'},dash:{[k:string]:string}={recettes:'',depenses:'7 5',cash:'',charges:''};return <div className="bg-white border rounded-2xl p-5"><h2 className="font-semibold text-sm mb-3">{title}</h2>{data.length===0?<div className="h-52 flex items-center justify-center text-sm text-slate-400">Aucune donnée sur cette période</div>:<><svg viewBox={`0 0 ${W} ${H}`} className="w-full h-56" role="img" aria-label={title}>{Array.from({length:ticks+1},(_,i)=>{const v=max-(max-min)*i/ticks,yy=y(v);return <g key={i}><line x1={L} y1={yy} x2={W-R} y2={yy} stroke="currentColor" opacity={v===0?.2:.07}/><text x={L-8} y={yy+4} textAnchor="end" fontSize="10" fill="currentColor" opacity=".55">{Math.round(v).toLocaleString('fr-FR')} €</text></g>})}{keys.map((k,ki)=>{const pts=data.map((d,i)=>`${x(i)},${y(d[k])}`).join(' ');return <g key={k} opacity={ki===0?1:.55}><polyline points={pts} fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" strokeDasharray={dash[k]}/>{data.map((d,i)=><circle key={i} cx={x(i)} cy={y(d[k])} r="3.5" fill="white" stroke="currentColor" strokeWidth="2"><title>{`${d.label} — ${labels[k]} : ${euro(d[k])}`}</title></circle>)}</g>})}{data.map((d,i)=><text key={d.label} x={x(i)} y={H-12} textAnchor="middle" fontSize="9" fill="currentColor" opacity=".5">{d.label}</text>)}</svg><div className="flex gap-5 text-xs text-slate-500">{keys.map((k,i)=><span key={k} className="flex items-center gap-1.5"><span className={`inline-block w-5 border-t-2 border-slate-700 ${i>0?'border-dashed opacity-60':''}`}/>{labels[k]}</span>)}</div></>}</div>}
