'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'

type Bien={id:string;nom:string;ville:string;type:string;prix_achat:number|null;date_acquisition:string|null}
type Lot={id:string;bien_id:string;type:string}
type Bail={id:string;bien_id:string;lot_id:string|null;date_entree:string;date_sortie:string|null;loyer_hc:number;actif:boolean}
type Quittance={id:string;bien_id:string;locataire_id:string;mois:string;total:number;envoyee:boolean}
type Depense={bien_id:string|null;montant:number;date_depense:string}
type Financement={bien_id:string;mensualite:number|null;assurance_mensuelle:number|null}
type Locataire={id:string;nom:string}

const HAB_BIEN=new Set(['appartement','maison','studio'])
const HAB_LOT=new Set(['appartement','studio','maison'])
const HORS=new Set(['parking','box','garage','cave','local_commercial','local-commercial','local commercial'])
const DAY=86400000
const n=(v:number|null|undefined)=>Number(v??0)
const euro=(v:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(v)
const ds=(s:string)=>new Date(`${s}T00:00:00`)
const days=(a:Date,b:Date)=>Math.max(0,Math.floor((b.getTime()-a.getTime())/DAY)+1)
function overlap(a1:Date,a2:Date,b1:Date,b2:Date){const s=new Date(Math.max(a1.getTime(),b1.getTime())),e=new Date(Math.min(a2.getTime(),b2.getTime()));return s<=e?days(s,e):0}
function fmtMonth(m:string){const[y,mo]=m.split('-');return new Date(+y,+mo-1,1).toLocaleDateString('fr-FR',{month:'short',year:'numeric'}).replace(/^./,c=>c.toUpperCase())}
function vacancy(bien:Bien,lotId:string|null,baux:Bail[],start:Date,end:Date){const acq=bien.date_acquisition?ds(bien.date_acquisition):start;const s=acq>start?acq:start;if(s>end)return null;const den=days(s,end);const intervals=baux.filter(b=>b.bien_id===bien.id&&(lotId?b.lot_id===lotId:!b.lot_id)).map(b=>({s:ds(b.date_entree),e:b.date_sortie?ds(b.date_sortie):end})).map(x=>({s:x.s<s?s:x.s,e:x.e>end?end:x.e})).filter(x=>x.s<=x.e).sort((a,b)=>a.s.getTime()-b.s.getTime());let occ=0,last:Date|null=null;for(const x of intervals){const ns=last&&x.s<=new Date(last.getTime()+DAY)?new Date(last.getTime()+DAY):x.s;if(ns<=x.e)occ+=days(ns,x.e);if(!last||x.e>last)last=x.e}return Math.max(0,Math.min(100,(den-occ)/den*100))}

export default function DashboardPage(){
 const[loading,setLoading]=useState(true),[year,setYear]=useState(new Date().getFullYear())
 const[biens,setBiens]=useState<Bien[]>([]),[lots,setLots]=useState<Lot[]>([]),[baux,setBaux]=useState<Bail[]>([]),[qs,setQs]=useState<Quittance[]>([]),[deps,setDeps]=useState<Depense[]>([]),[fins,setFins]=useState<Financement[]>([]),[locs,setLocs]=useState<Locataire[]>([])
 useEffect(()=>{const s=createClient();Promise.all([s.from('biens').select('id,nom,ville,type,prix_achat,date_acquisition'),s.from('lots').select('id,bien_id,type'),s.from('baux').select('id,bien_id,lot_id,date_entree,date_sortie,loyer_hc,actif'),s.from('quittances').select('id,bien_id,locataire_id,mois,total,envoyee').order('mois',{ascending:false}),s.from('depenses').select('bien_id,montant,date_depense'),s.from('financements').select('bien_id,mensualite,assurance_mensuelle'),s.from('locataires').select('id,nom')]).then(r=>{setBiens((r[0].data??[]) as Bien[]);setLots((r[1].data??[]) as Lot[]);setBaux((r[2].data??[]) as Bail[]);setQs((r[3].data??[]) as Quittance[]);setDeps((r[4].data??[]) as Depense[]);setFins((r[5].data??[]) as Financement[]);setLocs((r[6].data??[]) as Locataire[]);setLoading(false)})},[])
 const years=useMemo(()=>{const ys=new Set<number>([new Date().getFullYear()]);qs.forEach(q=>ys.add(+q.mois.slice(0,4)));deps.forEach(d=>d.date_depense&&ys.add(+d.date_depense.slice(0,4)));biens.forEach(b=>b.date_acquisition&&ys.add(+b.date_acquisition.slice(0,4)));const min=Math.min(...ys);for(let y=min;y<=new Date().getFullYear();y++)ys.add(y);return [...ys].sort((a,b)=>b-a)},[qs,deps,biens])
 const calc=useMemo(()=>{const now=new Date(),end=year===now.getFullYear()?now:new Date(year,11,31),start=new Date(year,0,1),prefix=`${year}-`;const recettes=qs.filter(q=>q.mois.startsWith(prefix)).reduce((a,q)=>a+n(q.total),0),depenses=deps.filter(d=>d.date_depense?.startsWith(prefix)).reduce((a,d)=>a+n(d.montant),0);const vacs:number[]=[];biens.forEach(b=>{const bl=lots.filter(l=>l.bien_id===b.id&&HAB_LOT.has(l.type));(bl.length?bl.map(l=>l.id):HAB_BIEN.has(b.type)?[null]:[]).forEach(id=>{const v=vacancy(b,id,baux,start,end);if(v!==null)vacs.push(v)})});const vacance=vacs.length?vacs.reduce((a,b)=>a+b,0)/vacs.length:null;const annual=baux.filter(b=>b.actif).reduce((a,b)=>a+n(b.loyer_hc)*12,0),prix=biens.reduce((a,b)=>a+n(b.prix_achat),0),rendement=prix>0?annual/prix*100:null;const monthlyDebt=fins.reduce((a,f)=>a+n(f.mensualite)+n(f.assurance_mensuelle),0),months=year===now.getFullYear()?now.getMonth()+1:12,marge=recettes-depenses,cash=marge-monthlyDebt*months,net=recettes>0?cash/recettes*100:null;const monthly=Array.from({length:12},(_,i)=>{const key=`${year}-${String(i+1).padStart(2,'0')}`,r=qs.filter(q=>q.mois===key).reduce((a,q)=>a+n(q.total),0),d=deps.filter(x=>x.date_depense?.startsWith(key)).reduce((a,x)=>a+n(x.montant),0);return{label:new Date(year,i,1).toLocaleDateString('fr-FR',{month:'short'}),recettes:r,depenses:d,cash:r-d-monthlyDebt}});return{recettes,depenses,vacance,rendement,marge,cash,net,monthly}},[year,biens,lots,baux,qs,deps,fins])
 const logements=biens.filter(b=>HAB_BIEN.has(b.type)).length+lots.filter(l=>HAB_LOT.has(l.type)).length,hors=biens.filter(b=>HORS.has(b.type)).length+lots.filter(l=>HORS.has(l.type)).length,locMap=new Map(locs.map(l=>[l.id,l.nom]));const recent=qs.slice(0,5)
 return <div className="p-6 max-w-6xl mx-auto"><div className="flex flex-wrap items-end justify-between gap-4 mb-7"><div><h1 className="text-2xl font-bold text-slate-900">Tableau de bord</h1><p className="text-sm text-slate-500 mt-1">Pilotage patrimonial et financier</p></div><label className="text-xs text-slate-500">Période<select value={year} onChange={e=>setYear(+e.target.value)} className="block mt-1 border rounded-lg px-3 py-2 bg-white text-sm text-slate-900">{years.map(y=><option key={y}>{y}</option>)}</select></label></div>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 mb-7"><K l="Logements" v={loading?'…':String(logements)} href="/dashboard/biens"/><K l="Biens hors logements" v={loading?'…':String(hors)} href="/dashboard/biens"/><K l="Dépenses" v={loading?'…':euro(calc.depenses)} href="/dashboard/depenses"/><K l="Taux de vacance" v={loading?'…':calc.vacance===null?'—':`${calc.vacance.toFixed(1)} %`} href="/dashboard/rentabilite"/><K l="Rentabilité brute" v={loading?'…':calc.rendement===null?'—':`${calc.rendement.toFixed(2)} %`} href="/dashboard/rentabilite"/><K l="Marge brute" v={loading?'…':euro(calc.marge)} href="/dashboard/rentabilite"/><K l="Cash-flow après dette" v={loading?'…':euro(calc.cash)} href="/dashboard/rentabilite"/><K l="Marge nette financière" v={loading?'…':calc.net===null?'—':`${calc.net.toFixed(1)} %`} href="/dashboard/rentabilite"/></div>
 <div className="grid lg:grid-cols-2 gap-5 mb-8"><Chart title="Recettes et dépenses" data={calc.monthly} keys={['recettes','depenses']}/><Chart title="Cash-flow mensuel" data={calc.monthly} keys={['cash']}/></div>
 <div><div className="flex items-center justify-between mb-4"><div><h2 className="text-sm font-semibold text-slate-500 uppercase tracking-wide">Historique des quittances</h2><p className="text-xs text-slate-400 mt-1">Les dernières quittances restent accessibles avec leur statut.</p></div><Link href="/dashboard/quittances" className="text-xs text-blue-600 hover:underline">Voir tout →</Link></div>{loading?<div className="h-32 bg-slate-100 rounded-2xl animate-pulse"/>:recent.length===0?<div className="bg-white border rounded-2xl p-8 text-center text-sm text-slate-400">Aucune quittance</div>:<div className="bg-white rounded-2xl border divide-y">{recent.map(q=><Link key={q.id} href={`/dashboard/quittances/${q.id}`} className="flex justify-between items-center px-5 py-4 hover:bg-slate-50"><div><p className="font-medium text-sm">{locMap.get(q.locataire_id)??'—'}</p><p className="text-xs text-slate-400">{fmtMonth(q.mois)}</p></div><div className="flex items-center gap-3"><b className="text-sm">{euro(q.total)}</b><span className={`text-xs px-2 py-1 rounded-full ${q.envoyee?'bg-green-100 text-green-700':'bg-amber-100 text-amber-700'}`}>{q.envoyee?'Envoyée':'À envoyer'}</span></div></Link>)}</div>}</div>
 <p className="mt-6 text-xs text-slate-400">Les KPI et graphiques suivent l’année sélectionnée. Le cash-flow déduit les dépenses, les mensualités de crédit et l’assurance emprunteur ; la fiscalité n’est pas encore incluse.</p></div>
}
function K({l,v,href}:{l:string;v:string;href:string}){return <Link href={href} className="bg-white border rounded-2xl p-5 hover:shadow-md transition-shadow"><p className="text-xs uppercase tracking-wide text-slate-500">{l}</p><p className="text-xl font-bold mt-1">{v}</p></Link>}
function Chart({title,data,keys}:{title:string;data:{label:string;recettes:number;depenses:number;cash:number}[];keys:('recettes'|'depenses'|'cash')[]}){const vals=data.flatMap(d=>keys.map(k=>d[k])),max=Math.max(1,...vals.map(Math.abs)),W=600,H=210,pad=28;const pts=(k:'recettes'|'depenses'|'cash')=>data.map((d,i)=>`${pad+i*(W-2*pad)/11},${H/2-d[k]/max*(H/2-pad)}`).join(' ');return <div className="bg-white border rounded-2xl p-5"><h2 className="font-semibold text-sm mb-4">{title}</h2><svg viewBox={`0 0 ${W} ${H}`} className="w-full h-52" role="img" aria-label={title}><line x1={pad} y1={H/2} x2={W-pad} y2={H/2} stroke="currentColor" opacity=".15"/>{keys.map((k,idx)=><polyline key={k} points={pts(k)} fill="none" stroke="currentColor" opacity={idx===0?1:.45} strokeWidth={idx===0?3:2}/>) }{data.map((d,i)=><text key={d.label} x={pad+i*(W-2*pad)/11} y={H-5} textAnchor="middle" fontSize="10" fill="currentColor" opacity=".5">{d.label}</text>)}</svg><div className="flex gap-4 text-xs text-slate-500">{keys.map(k=><span key={k} className="capitalize">— {k}</span>)}</div></div>}
