'use server'
import {createClient} from '@/lib/supabase/server'
import {revalidatePath} from 'next/cache'
const TYPES=['appartement','studio','cave','garage','box','parking','local_commercial','autre']
export async function ajouterLot(bienId:string,fd:FormData){
 const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)return{error:'Vous devez être connecté.'}
 const{data:bien,error:be}=await s.from('biens').select('id,type').eq('id',bienId).eq('proprietaire_id',user.id).single();if(be||!bien||!['immeuble','immeuble_rapport'].includes(bien.type))return{error:'Immeuble introuvable.'}
 const type=String(fd.get('type')||''),hab=['appartement','studio'].includes(type),ratt=['box','parking','garage','cave'].includes(type);if(!TYPES.includes(type))return{error:'Choisissez un type de lot.'}
 const numeric=(key:string)=>{const v=String(fd.get(key)||'').trim();return v?Number(v):null};const surface=numeric('surface_m2'),pieces=numeric('nb_pieces'),prix=numeric('prix_mensuel'),low=numeric('estimation_conso_basse'),high=numeric('estimation_conso_haute');if(surface==null||!Number.isFinite(surface)||surface<=0)return{error:'Renseignez une surface supérieure à zéro.'};if([pieces,prix,low,high].some(v=>v!=null&&(!Number.isFinite(v)||v<0)))return{error:'Les valeurs doivent être des nombres positifs.'};if(hab&&pieces!=null&&(!Number.isInteger(pieces)||pieces<1))return{error:'Le nombre de pièces doit être un entier supérieur à zéro.'};if(hab&&low!=null&&high!=null&&high<low)return{error:'L’estimation haute doit être supérieure ou égale à l’estimation basse.'}
 const location=String(fd.get('type_location')||'');if(hab&&!['meuble','non_meuble'].includes(location))return{error:'Choisissez un type de location.'};const dpe=String(fd.get('dpe')||'');if(hab&&dpe&&!['A','B','C','D','E','F','G'].includes(dpe))return{error:'DPE invalide.'}
 const{data:lots,error:le}=await s.from('lots').select('numero_lot').eq('bien_id',bienId).eq('proprietaire_id',user.id);if(le)return{error:le.message};const numbers=(lots??[]).map(l=>Number(/^Lot (\d+)$/.exec(l.numero_lot??'')?.[1]||0));const numero=`Lot ${Math.max(0,...numbers)+1}`;
 const{error}=await s.from('lots').insert({bien_id:bienId,proprietaire_id:user.id,numero_lot:numero,nom_personnalise:String(fd.get('nom_personnalise')||'').trim()||null,type,surface_m2:surface,nb_pieces:hab?pieces:null,type_location:hab?location:null,specificite:hab?(String(fd.get('specificite')||'')||null):null,dpe:hab?(dpe||null):null,estimation_conso_annuelle_basse:hab?low:null,estimation_conso_annuelle_haute:hab?high:null,prix_mensuel:ratt?prix:null,annexes:hab?fd.getAll('annexes').filter(v=>['cave','parking','box','balcon','terrasse','grenier'].includes(String(v))):[],parent_lot_id:null,rattachement_type:null});if(error)return{error:error.message}
 const{count,error:ce}=await s.from('lots').select('id',{count:'exact',head:true}).eq('bien_id',bienId).eq('proprietaire_id',user.id);let warning:string|undefined;if(!ce&&count!=null){const{error:e}=await s.from('biens').update({nb_lots:count}).eq('id',bienId).eq('proprietaire_id',user.id);if(e)warning='Le lot est créé, mais le compteur de lots n’a pas pu être actualisé.'}else warning='Le lot est créé, mais le compteur de lots n’a pas pu être actualisé.';
 revalidatePath(`/dashboard/biens/${bienId}`);revalidatePath(`/dashboard/biens/${bienId}/modifier`);revalidatePath('/dashboard/biens');revalidatePath('/dashboard');return{ok:true,warning}
}
